### ISSUE TITLE
append is not a measure?

### ISSUE THREAD

**Issue by conal** [nikivazou/EquationalReasoningInLiquidHaskell#3]
https://github.com/nikivazou/EquationalReasoningInLiquidHaskell/blob/414de1635238f92a52c989cff90e1a800c2a75af/src/02-Reasoning-About-Programs.lhs#L71-L74

https://github.com/nikivazou/EquationalReasoningInLiquidHaskell/blob/414de1635238f92a52c989cff90e1a800c2a75af/src/02-Reasoning-About-Programs.lhs#L118

It seems to me that append really does satisfy the criteria for being a measure, considering that it (like all Haskell functions) takes just a single argument, there's one equation per constructor, and the definition body calls only primitive functions and measures. Unless maybe cons is not considered a primitive function.

Is there some fundamental reason that curried functions can't measures? Is there a helpful restriction on the *codomain* of a measure, perhaps one that disqualifies function-valued codomains?

**Comment by conal** [comment]
Perhaps @ranjitjhala has some insight on this question, since it seems that [*Type-based data structure verification*](https://ranjitjhala.github.io/static/type-based_data_structure_verification.pdf) introduced measures and defines them similarly.

**Comment by ranjitjhala** [comment]
Hi @conal (though we didn't know it at the time) really measures turned out to be a way for "decorating" the types of data constructors. So, when you write, e.g.

```haskell
{-@ measure size @-}
size :: [a] -> Int 
size [] = 0
size (x:xs) = 1 + size xs

{-@ measure null @-}
null :: [a] -> Bool
null [] = True
null (x:xs) = False
```

Internally the above are converted to "strengthened" versions for the 
constructors `:` and `[]` so its as if, we had defined the list type as:

```
data [a] where
  (:) :: x:a -> xs:[a] -> {v:[a] | size v = 1 + size xs && null v = false}
  [] :: {v:[a] | size v = 0 && null v = true}
```

So really the "bodies" of the measures get translated to refinements 
on the output types of the corresponding constructors. 

Now, your observation is correct: historically, we did not support 
function-valued objects in the refinements -- they were limited to 
first-order values like int, bool, bit-vectors, sets -- things that the 
SMT solver supports natively. Hence, we disallowed function-valued 
co-domains  for measures. 

However, with the recent reflection work we have started to support 
it, so one could in principle revisit this choice as you suggest! 

Does that help?

**Comment by conal** [comment]
> Hi @conal (though we didn't know it at the time) really measures turned out to be a way for "decorating" the types of data constructors. 
> ...
> So really the "bodies" of the measures get translated to refinements
> on the output types of the corresponding constructors.

Very elegant!

> ... Hence, we disallowed function-valued
> co-domains for measures.
> 
> However, with the recent reflection work we have started to support
> it, so one could in principle revisit this choice as you suggest!

Wonderful!

Thanks for the explanations and the lovely work.

**Comment by conal** [comment]
@nikivazou: @ranjitjhala provided the enlightenment I sought. You might reword the passages above or leave as they are.  Please do as you wish with this issue and close it as your discretion.

**Comment by nikivazou** [comment]
Sure! I agree with everything and find the idea of revisiting what is a measure very interesting!
